---
  - name: Install nginx
    apt:
      name: nginx
      state: present

  - name: Start NGiNX
    service:
      name: nginx
      state: started

  - name: copy nginx site.conf
    template:
      src: site.conf.j2
      dest: /etc/nginx/sites-enabled/{{ domain }}
      owner: root
      group: root
      mode: '0644'
    notify: 
      - restart nginx